GET http://localhost:3000/api/post/

###
GET http://localhost:3000/api/post/66ec780bb77c9a981ae7cb42

###
POST http://localhost:3000/api/post/create
Content-Type: application/json

{
    "title": "My second post",
    "content": "Hello World2",
    "authorId": "66ec75d65faca3e7b3b2eb47"
}

###
PATCH http://localhost:3000/api/post/update
Content-Type: application/json

{
    "id": "66ec780bb77c9a981ae7cb42",
    "title": "My first post",
    "content": "Hello World3",
    "author": "66ec75d65faca3e7b3b2eb47"   
}

###
DELETE http://localhost:3000/api/post/delete/66ed9cecf9ddac151a2d8f5e