GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/66ec75d65faca3e7b3b2eb47

###
POST http://localhost:3000/api/user/create
Content-Type: application/json

{
    "name": "Paulo Meneghel",
    "location": "Brazil"
}

###
PATCH http://localhost:3000/api/user/
Content-Type: application/json

{
    "id": "66ec75d65faca3e7b3b2eb47",
    "name": "José Tavares",
    "location": "Lisbon"
}

###
DELETE http://localhost:3000/api/user/delete/66ed9876cc28322741e9abf2

