GET http://localhost:3000/user

###

GET http://localhost:3000/user/66ead0a88cdc9c27990b36c7

###
POST http://localhost:3000/user/insert
Content-Type: application/json

{
    "name": "Joe Lenou",
    "location": "Braco do Norte"
}

###
PATCH http://localhost:3000/user/update
Content-Type: application/json

{
    "id": "66ead0a88cdc9c27990b36c7",
    "name": "José Tavares",
    "location": "Lisbon"
}

DELETE http://localhost:3000/user
